[package]
name = "test_path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl-include = "0.5.1"
uni-path = "1.51.1"
